Repository sipe-team/side, pull requests merged in 2024-12, with the labels that each got.

#42 docs(readme): README 업데이트
  .github/CONTRIBUTING.md
  README.md
  public/assets/og-image.png
Labels: documentation

#50 feat( switch): Switch 컴포넌트 구현
  packages/switch/.storybook/main.ts
  packages/switch/.storybook/preview.ts
  packages/switch/package.json
  packages/switch/src/Switch.module.css
  packages/switch/src/Switch.stories.tsx
  packages/switch/src/Switch.test.tsx
  packages/switch/src/Switch.tsx
  packages/switch/src/constants/size.ts
  packages/switch/src/env.d.ts
  packages/switch/src/hooks/useCheckedController.tsx
  packages/switch/src/index.ts
  packages/switch/tsconfig.json
  packages/switch/tsup.config.ts
  packages/switch/vitest.config.ts
  packages/switch/vitest.setup.ts
  pnpm-lock.yaml
Labels: good first PR 🎉

#52 fix(test): add exclude in root vitest.config.ts
  packages/Input/src/Input.module.css.d.ts
  packages/Input/src/env.d.ts
  vitest.config.ts
Labels: enhancement

#43 feat(tooltip): Tooltip 컴포넌트 구현
  packages/tooltip/.storybook/main.ts
  packages/tooltip/.storybook/preview.ts
  packages/tooltip/package.json
  packages/tooltip/src/Tooltip.module.css
  packages/tooltip/src/Tooltip.stories.tsx
  packages/tooltip/src/Tooltip.test.tsx
  packages/tooltip/src/Tooltip.tsx
  packages/tooltip/src/env.d.ts
  packages/tooltip/src/hooks/useTooltip/index.ts
  packages/tooltip/src/hooks/useTooltip/useTooltip.md
  packages/tooltip/src/hooks/useTooltip/useTooltip.tsx
  packages/tooltip/src/index.ts
  packages/tooltip/tsconfig.json
  packages/tooltip/tsup.config.ts
  packages/tooltip/vitest.config.ts
  packages/tooltip/vitest.setup.ts
  pnpm-lock.yaml
Labels: good first PR 🎉
