Repository sipe-team/side, pull requests merged in 2025-01, with the labels that each got.

#68 docs: README logo update
  public/assets/og-image.png
Labels: documentation

#67 chore: initial setup for pre-commit, commitlinting
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  commitlint.config.ts
  package.json
  pnpm-lock.yaml
Labels: documentation

#44 feat(button): Button 컴포넌트 구현
  packages/button/.storybook/main.ts
  packages/button/.storybook/preview.ts
  packages/button/package.json
  packages/button/src/Button.module.css
  packages/button/src/Button.stories.tsx
  packages/button/src/Button.test.tsx
  packages/button/src/Button.tsx
  packages/button/src/env.d.ts
  packages/button/src/index.ts
  packages/button/tsconfig.json
  packages/button/tsup.config.ts
  packages/button/vitest.config.ts
  packages/button/vitest.setup.ts
  pnpm-lock.yaml
Labels: good first PR 🎉

#74 chore: git repository url 업데이트
  .github/CONTRIBUTING.md
  .templates/component/package.json
  README.md
  packages/Input/package.json
  packages/badge/package.json
  packages/button/package.json
  packages/card/package.json
  packages/divider/package.json
  packages/radio-group/package.json
  packages/side/package.json
  packages/skeleton/package.json
  packages/switch/package.json
  packages/tokens/package.json
  packages/tooltip/package.json
  packages/typography/package.json
Labels: documentation

#75 Update release commit message
  .github/workflows/release.yaml
  pnpm-lock.yaml
Labels: bug

#82 feat(flex): add flex component
  .changeset/ninety-icons-invite.md
  packages/flex/.storybook/main.ts
  packages/flex/.storybook/preview.ts
  packages/flex/global.d.ts
  packages/flex/package.json
  packages/flex/src/Flex.module.css
  packages/flex/src/Flex.stories.tsx
  packages/flex/src/Flex.test.tsx
  packages/flex/src/Flex.tsx
  packages/flex/src/index.ts
  packages/flex/tsconfig.json
  packages/flex/tsup.config.ts
  packages/flex/vitest.config.ts
  packages/flex/vitest.setup.ts
  packages/side/package.json
  packages/side/src/index.ts
  pnpm-lock.yaml
Labels: enhancement

#87 chore(husky): add pre-push githook for branch naming convention
  .husky/pre-push
Labels: documentation

#91 ci(husky): disabled git hook on CI
  .github/workflows/release.yaml
Labels: bug

#45 feat(avatar): avatar 컴포넌트 구현
  packages/avatar/.storybook/main.ts
  packages/avatar/.storybook/preview.ts
  packages/avatar/global.d.ts
  packages/avatar/package.json
  packages/avatar/src/Avatar.module.css
  packages/avatar/src/Avatar.stories.tsx
  packages/avatar/src/Avatar.test.tsx
  packages/avatar/src/Avatar.tsx
  packages/avatar/src/index.ts
  packages/avatar/tsconfig.json
  packages/avatar/tsup.config.ts
  packages/avatar/vitest.config.ts
  packages/avatar/vitest.setup.ts
  pnpm-lock.yaml
Labels: good first PR 🎉

#89 docs: add bug report
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/component_design.md
Labels: documentation

#97 Chore/storybook theme
  .storybook/main.ts
  .storybook/manager.ts
  .templates/component/src/Component.stories.tsx
  docs/introduction.mdx
  package.json
  packages/Input/src/Input.stories.tsx
  packages/avatar/src/Avatar.stories.tsx
  packages/badge/src/Badge.stories.tsx
  packages/button/src/Button.stories.tsx
  packages/card/src/Card.stories.tsx
  packages/divider/src/Divider.stories.tsx
  packages/flex/src/Flex.stories.tsx
  packages/icon/src/Icons.stories.tsx
  packages/radio-group/src/RadioGroup.stories.tsx
  packages/skeleton/src/Skeleton.stories.tsx
  packages/switch/src/Switch.stories.tsx
  packages/tokens/src/Tokens.stories.tsx
  packages/tooltip/src/Tooltip.stories.tsx
  packages/typography/src/Typography.stories.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
  public/assets/favicon.ico
  public/assets/sipe_brand_logo.png
Labels: documentation

#95 chore(eslint): enhance eslint
  biome.json
  eslint.config.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#99 fix: Issue Template Parsing Issue
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/component_design.md
Labels: documentation

#100 Chore/readme update
  .storybook/main.ts
  .storybook/manager.ts
  README.md
  docs/introduction.mdx
  package.json
Labels: documentation

#103 docs(documentation): add documentation, feature request issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#101 refactor(card): add custom ratio for better flexibility
  .changeset/eighty-apricots-punch.md
  README.md
  packages/card/src/Card.stories.tsx
  packages/card/src/Card.test.tsx
  packages/card/src/Card.tsx
Labels: enhancement

#69 docs: update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#108 ci(release): add --ignore flag for template package name
  .github/workflows/release.yaml
  package.json
Labels: bug

#116 docs(codeowner): add `@jiji-hoon96` as one of code owners
  .github/CODEOWNERS
Labels: documentation

#113 chore(template): add private:true package.json in template
  .github/workflows/release.yaml
  .templates/component/package.json
  package.json
  scripts/createComponent.ts
Labels: bug

#114 chore(script): remove unstable_ts_config flag from script
  .templates/component/package.json
  .vscode/settings.json
  biome.json
  package.json
  packages/Input/package.json
  packages/avatar/src/Avatar.tsx
  packages/badge/package.json
  packages/button/package.json
  packages/card/package.json
  packages/divider/package.json
  packages/flex/package.json
  packages/icon/package.json
  packages/radio-group/package.json
  packages/skeleton/package.json
  packages/switch/package.json
  packages/tokens/package.json
  packages/tooltip/package.json
  packages/tooltip/src/Tooltip.tsx
  packages/typography/package.json
  pnpm-lock.yaml
  scripts/createComponent.ts
Labels: documentation

#111 feat(www): add side homepage
  .gitignore
  .templates/component/package.json
  packages/Input/package.json
  packages/avatar/package.json
  packages/badge/package.json
  packages/button/package.json
  packages/card/package.json
  packages/checkbox/package.json
  packages/divider/package.json
  packages/flex/package.json
  packages/icon/package.json
  packages/radio-group/package.json
  packages/skeleton/package.json
  packages/switch/package.json
  packages/tokens/package.json
  packages/tooltip/package.json
  packages/typography/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vitest.config.ts
  www/README.md
  www/docs/components/avatar.mdx
  www/docs/intro.md
  www/docusaurus.config.ts
  www/package.json
  www/sidebars.ts
  www/src/HomepageFeatures/index.module.css
  www/src/HomepageFeatures/index.tsx
  www/src/custom.css
  www/src/pages/index.module.css
  www/src/pages/index.tsx
  www/static/.nojekyll
  www/static/img/docusaurus-social-card.jpg
  www/static/img/docusaurus.png
  www/static/img/favicon.ico
  www/static/img/logo.svg
  www/static/img/undraw_docusaurus_mountain.svg
  www/static/img/undraw_docusaurus_react.svg
  www/static/img/undraw_docusaurus_tree.svg
  www/tsconfig.json
Labels: documentation

#117 Update storybook intro
  docs/introduction.mdx
  packages/checkbox/src/Checkbox.stories.tsx
Labels: documentation

#119 docs(docs): add installation guide
  www/docs/components/_category_.json
  www/docs/intro.md
  www/docs/overview/Installation.mdx
  www/docs/overview/_category_.json
  www/docusaurus.config.ts
  www/sidebars.ts
  www/src/pages/index.tsx
Labels: documentation

#122 feat(reset): Create base CSS reset package
  .changeset/dry-poets-fly.md
  packages/reset/.storybook/main.ts
  packages/reset/.storybook/preview.ts
  packages/reset/README.md
  packages/reset/global.d.ts
  packages/reset/package.json
  packages/reset/src/Reset.module.css
  packages/reset/src/Reset.stories.tsx
  packages/reset/src/Reset.test.tsx
  packages/reset/src/Reset.tsx
  packages/reset/src/global.css
  packages/reset/src/index.ts
  packages/reset/tsconfig.json
  packages/reset/tsup.config.ts
  packages/reset/vitest.config.ts
  packages/reset/vitest.setup.ts
  pnpm-lock.yaml
Labels: enhancement
